src/Entity/Document.php
<?php

namespace App\Entity;

use App\Repository\DocumentRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: DocumentRepository::class)]
class Document
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255)]
    private ?string $file_path = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\ManyToOne(inversedBy: 'documents')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $created_by = null;

    #[ORM\Column(type: Types::BOOLEAN)]
    private bool $is_admin_only = false;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getFilePath(): ?string
    {
        return $this->file_path;
    }

    public function setFilePath(string $file_path): static
    {
        $this->file_path = $file_path;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getCreatedBy(): ?User
    {
        return $this->created_by;
    }

    public function setCreatedBy(?User $created_by): static
    {
        $this->created_by = $created_by;

        return $this;
    }

    public function getIsAdminOnly(): ?bool
    {
        return $this->is_admin_only;
    }

    public function setIsAdminOnly(bool $is_admin_only): static
    {
        $this->is_admin_only = $is_admin_only;

        return $this;
    }

    public function getFileExtension(): ?string
    {
        $filename = $this->getTitle();
        return pathinfo($filename, PATHINFO_EXTENSION);
    }
    
}

src/Controller/DocumentController.php
<?php

namespace App\Controller;

use App\Entity\User;
use App\Entity\Document;
use App\Form\DocumentFormType;
use App\Repository\DocumentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\Security\Http\Attribute\IsGranted;
use Symfony\Component\String\Slugger\SluggerInterface;

class DocumentController extends AbstractController
{
    #[Route('/documents', name: 'app_user_documents')]
    public function index(DocumentRepository $documentRepository, Request $request): Response
    {
        $user = $this->getUser();
    
        if (!$user instanceof User) {
            throw $this->createAccessDeniedException('Vous devez être connecté pour accéder à vos documents.');
        }
    
        $searchTerm = $request->query->get('search');
        $dateFilter = $request->query->get('date');

        $documents = $documentRepository->findBy(['created_by' => $user]);
    
        if ($searchTerm) {
            $documents = array_filter($documents, function($document) use ($searchTerm) {
                return stripos($document->getTitle(), $searchTerm) !== false || stripos($document->getDescription(), $searchTerm) !== false;
            });
        }
    
        if ($dateFilter) {
            $documents = array_filter($documents, function($document) use ($dateFilter) {
                return $document->getCreatedAt()->format('d-m-Y') === $dateFilter;
            });
        }
    
        return $this->render('pages/document/showDocuments.html.twig', [
            'documents' => $documents,
            'searchTerm' => $searchTerm,
        ]);
    }
    
    #[Route('/document/new', name: 'app_document_new')]
    public function create(Request $request, DocumentRepository $documentRepository, EntityManagerInterface $em, SluggerInterface $slugger): Response
    {
        $user = $this->getUser();
    
        if (!$user instanceof User) {
            throw $this->createAccessDeniedException('Vous devez être connecté pour créer un document.');
        }
    
        $userDocuments = $documentRepository->findBy(['created_by' => $user]);
        $totalSize = array_reduce($userDocuments, function ($carry, $doc) {
            return $carry + filesize($doc->getFilePath());
        }, 0);
    
        if ($totalSize >= 20 * 1024 * 1024 * 1024) { // 20 Go
            $this->addFlash('error', 'Vous ne pouvez pas dépasser 20 Go de documents.');
            return $this->redirectToRoute('app_user_documents');
        }
    
        $document = new Document();
        $form = $this->createForm(DocumentFormType::class, $document);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $document->setCreatedBy($user);
            $document->setCreatedAt(new \DateTimeImmutable());
            $document->setUpdatedAt(new \DateTimeImmutable());
    
            $pdfFile = $form->get('file')->getData();
            if ($pdfFile) {
                if ($pdfFile->getSize() > 5 * 1024 * 1024 * 1024) { // 5 Go
                    $this->addFlash('error', 'Le document ne doit pas dépasser 5 Go.');
                    return $this->redirectToRoute('app_document_new');
                }
    
                $originalFilename = pathinfo($pdfFile->getClientOriginalName(), PATHINFO_FILENAME);
                $extension = $pdfFile->guessExtension();
    
                $safeFilename = $slugger->slug($originalFilename);
                $newFilename = $safeFilename . '-' . $user->getLastName() . '-' . $user->getFirstName() . '.' . $extension;
    
                $uploadDir = $this->getParameter('kernel.project_dir') . '/public/uploads/documents/' . $user->getLastName() . '-' . $user->getFirstName();
    
                if (!is_dir($uploadDir)) {
                    mkdir($uploadDir, 0777, true);
                }
    
                // Vérification si le fichier existe déjà
                if (file_exists($uploadDir . '/' . $newFilename)) {
                    $this->addFlash('error', 'Un fichier ayant le même nom existe déjà, modifiez son nom avant de réessayer.');
                    return $this->redirectToRoute('app_document_new');
                }
    
                try {
                    $pdfFile->move($uploadDir, $newFilename);
                } catch (FileException $e) {
                    $this->addFlash('error', 'Erreur lors du téléchargement du document.');
                    return $this->redirectToRoute('app_document_new');
                }
    
                $document->setFilePath('uploads/documents/' . $user->getLastName() . '-' . $user->getFirstName() . '/' . $newFilename);
                $document->setTitle($safeFilename . '.' . $extension);
            }
    
            $em->persist($document);
            $em->flush();
    
            return $this->redirectToRoute('app_user_documents');
        }
    
        return $this->render('pages/document/newDocument.html.twig', [
            'form' => $form->createView(),
        ]);
    }

    #[Route('/document/{id}', name: 'app_document_show')]
    public function show(Document $document): Response
    {
        $user = $document->getCreatedBy();
        
        if ($user === null) {
            throw $this->createNotFoundException('User not found');
        }
    
        $filePath = $document->getFilePath();
        $fullFilePath = $this->getParameter('kernel.project_dir') . '/public/' . $filePath;
    
        
        dump($fullFilePath);
    
        if (!file_exists($fullFilePath)) {
            throw $this->createNotFoundException('Le fichier n\'existe pas. Chemin : ' . $fullFilePath);
        }
    
        return $this->render('pages/document/showDocument.html.twig', [
            'document' => $document,
            'filePath' => $filePath,
        ]);
    }

    #[Route('/document/{id}/download', name: 'app_document_download')]
    public function download(Document $document): Response
    {

        $filePath = $document->getFilePath();
        $fullFilePath = $this->getParameter('kernel.project_dir') . '/public/' . $filePath;


        if (!file_exists($fullFilePath)) {
            throw $this->createNotFoundException('Le fichier n\'existe pas.');
        }

        return $this->file($fullFilePath);
    }

    #[Route('/document/{id}/edit', name: 'app_document_edit')]
    public function edit(Request $request, Document $document, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(DocumentFormType::class, $document);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $document->setUpdatedAt(new \DateTimeImmutable());
            $em->flush();

            return $this->redirectToRoute('app_user_documents');
        }

        return $this->render('pages/document/editDocument.html.twig', [
            'form' => $form->createView(),
            'document' => $document,
        ]);
    }

    #[Route('/document/{id}/delete', name: 'app_document_delete')]
    public function delete(Document $document, EntityManagerInterface $em): Response
    {
        if ($document->getFilePath() && file_exists($document->getFilePath())) {
            unlink($document->getFilePath());
        }

        $em->remove($document);
        $em->flush();

        return $this->redirectToRoute('app_user_documents');
    }

    #[Route('/admin/documents', name: 'app_admin_documents')]
    #[IsGranted('ROLE_ADMIN')]
    public function adminDocuments(DocumentRepository $documentRepository, Request $request): Response
    {
        $user = $this->getUser();
        
        if (!$user instanceof User) {
            throw $this->createAccessDeniedException('Vous devez être connecté pour accéder à vos documents.');
        }
    
        $searchTerm = $request->query->get('search');
        $dateFilter = $request->query->get('date');
        
        if ($this->isGranted('ROLE_ADMIN')) {
            $documents = $documentRepository->findAll();
        } else {
            $documents = $documentRepository->findBy(['created_by' => $user, 'is_admin_only' => false]);
        }

        if ($searchTerm) {
            $documents = array_filter($documents, function($document) use ($searchTerm) {
                return stripos($document->getTitle(), $searchTerm) !== false || stripos($document->getDescription(), $searchTerm) !== false;
            });
        }
    
        if ($dateFilter) {
            $documents = array_filter($documents, function($document) use ($dateFilter) {
                return $document->getCreatedAt()->format('d-m-Y') === $dateFilter;
            });
        }
    
        return $this->render('pages/document/showAdminDocuments.html.twig', [
            'documents' => $documents,
            'searchTerm' => $searchTerm,
        ]);
    }

    #[Route('/admin/document/new', name: 'app_admin_document_new')]
    #[IsGranted('ROLE_ADMIN')]
    public function createAdminDocument(Request $request, DocumentRepository $documentRepository, EntityManagerInterface $em, SluggerInterface $slugger): Response
    {
        $user = $this->getUser();
    
        if (!$this->isGranted('ROLE_ADMIN')) {
            throw $this->createAccessDeniedException('Accès réservé aux administrateurs.');
        }
    
        $document = new Document();
        $form = $this->createForm(DocumentFormType::class, $document);
        $form->handleRequest($request);
    
        if ($form->isSubmitted() && $form->isValid()) {
            $document->setCreatedBy($user);
            $document->setCreatedAt(new \DateTimeImmutable());
            $document->setUpdatedAt(new \DateTimeImmutable());
            $document->setIsAdminOnly(true);
    

templates/pages/document/editAdminDocument.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier le Document{% endblock %}

{% block body %}
    <h1>Modifier le Document : {{ document.title }}</h1>

    {% for label, messages in app.flashes %}
        <div class="alert alert-{{ label }}">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endfor %}

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-success">Modifier</button>
    {{ form_end(form) }}

    <a href="{{ path('app_admin_documents') }}" class="btn btn-secondary"> Retour aux documents</a>
{% endblock %}

templates/pages/document/editDocument.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier le Document{% endblock %}

{% block body %}
    <h1>Modifier le Document : {{ document.title }}</h1>

    {% for label, messages in app.flashes %}
        <div class="alert alert-{{ label }}">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endfor %}

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="btn btn-success">Modifier</button>
    {{ form_end(form) }}

    <a href="{{ path('app_user_documents') }}" class="btn btn-secondary">Retour à mes Documents</a>
{% endblock %}

templates/pages/document/newAdminDocument.html.twig
{% extends 'base.html.twig' %}

{% block title %}<i class="fa-solid fa-file-circle-question"></i> Ajouter un Document Administrateur{% endblock %}

{% block body %}
    <h1>Ajouter un Document Administrateur</h1>

    
    <a href="{{ path('app_user_documents') }}"><i class="fa-solid fa-arrow-left-long"></i> Retour au documents administrateur</a>

    {% for label, messages in app.flashes %}
        <div class="alert alert-{{ label }}">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endfor %}

    <form method="post" action="{{ path('app_admin_document_new') }}" enctype="multipart/form-data" class="document-form">
    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit" ><i class="fa-solid fa-shield-halved"></i> Ajouter le Document</button>
    {{ form_end(form) }}
    </form>
{% endblock %}

templates/pages/document/newDocument.html.twig
{% extends 'base.html.twig' %}

{% block title %}<i class="fa-solid fa-file-circle-question"></i> Ajouter un Document{% endblock %}

{% block body %}
    <h1>Ajouter un Document</h1>

        <a href="{{ path('app_user_documents') }}"><i class="fa-solid fa-arrow-left-long"></i> Retour à mes Documents</a>

    {% for label, messages in app.flashes %}
        <div class="alert alert-{{ label }}">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endfor %}

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit">Ajouter</button>
    {{ form_end(form) }}

{% endblock %}

templates/pages/document/showAdminDocument.html.twig
{% extends 'base.html.twig' %}

{% block title %}Document Admin - {{ document.title }}{% endblock %}

{% block body %}
    <a href="{{ path('app_admin_documents') }}" class="btn btn-secondary"><i class="fa-solid fa-arrow-left-long"></i> Retour à mes documents</a>
    <br>
    <h1>{{ document.title }}</h1>
    <br>
    <h5><em>**Cette page est un aperçu du fichier. Des erreurs visuelles telles que des manques de contenu, de couleurs, de graphiques, et d'autres éléments peuvent survenir. Cela n'altère en aucun cas votre fichier.**</em></h5>
    <a href="{{ path('app_admin_document_download', {id: document.id}) }}" class="button-send">Télécharger</a>
    <a href="{{ path('app_admin_document_delete', {id: document.id}) }}" class="button-delete" onclick="return confirm('Êtes-vous sûr de vouloir supprimer {{ document.title }} de votre dossier ?')">Supprimer</a>
    <br>
        {% set extension = document.getFileExtension() %}
        
        {% if extension == 'pdf' %}
            <iframe src="{{ asset(filePath) }}" width="100%" height="600" style="border: none;">
                <p>Votre navigateur ne supporte pas l'affichage des PDF. Cliquez <a href="{{ asset(filePath) }}">ici</a> pour télécharger le fichier.</p>
            </iframe>

        {% elseif extension in ['doc', 'docx'] %}
            <div id="word-output" class="word-content"></div>
            <script>
                var filePath = "{{ asset(filePath) }}";
                fetch(filePath)
                    .then(response => response.arrayBuffer())
                    .then(data => {
                        mammoth.convertToHtml({ arrayBuffer: data })
                            .then(function(result) {
                                
                                document.getElementById('word-output').innerHTML = result.value; // Le contenu HTML
                            })
                            .catch(function(err) {
                                console.error("Erreur lors de la conversion du fichier Word:", err);
                            });
                    })
                    .catch(function(error) {
                        console.error('Erreur de lecture du fichier Word:', error);
                    });
            </script>
        {% elseif extension in ['xls', 'xlsx'] %}
            <div id="excel-output" class="custom-excel-table"></div>
            <script>
                var filePath = "{{ asset(filePath) }}";
                fetch(filePath)
                    .then(response => response.arrayBuffer())
                    .then(data => {
                        var workbook = XLSX.read(data, { type: 'array' });
                        var sheet = workbook.Sheets[workbook.SheetNames[0]];

                        var html = XLSX.utils.sheet_to_html(sheet, {
                            cellHTML: false,
                            raw: true
                        });

                        var tempDiv = document.createElement('div');
                        tempDiv.innerHTML = html;

                        for (var cell in sheet) {
                            if (cell[0] === '!') continue;
                            var cellData = sheet[cell];
                            var cellElement = tempDiv.querySelector(`[data-cell="${cell}"]`);

                            if (cellElement) {
                                if (cellData.s) {
                                    if (cellData.s.fill) {
                                        cellElement.style.backgroundColor = cellData.s.fill.fgColor.rgb 
                                            ? `#${cellData.s.fill.fgColor.rgb}` 
                                            : '';
                                    }
                                    if (cellData.s.font) {
                                        cellElement.style.color = cellData.s.font.color 
                                            ? `#${cellData.s.font.color.rgb}` 
                                            : '';
                                    }
                                }
                                cellElement.setAttribute('data-cell', cell);
                            }
                        }

                        document.getElementById('excel-output').innerHTML = tempDiv.innerHTML;
                    })
                    .catch(function(error) {
                        console.error('Erreur de lecture du fichier Excel:', error);
                    });
            </script>
        {% else %}
            <p>Le format de fichier n'est pas pris en charge pour l'affichage en ligne. Cliquez <a href="{{ asset(filePath) }}">ici</a> pour télécharger le fichier.</p>
        {% endif %}
{% endblock %}

templates/pages/document/showAdminDocuments.html.twig
{% extends 'base.html.twig' %}

{% block title %}<i class="fa-solid fa-folder-open"></i> Documents Admin{% endblock %}

{% block body %}
    <h1>Documents réservés aux administrateurs</h1>

    {% for label, messages in app.flashes %}
        <div class="alert alert-{{ label }}">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endfor %}

    <br>
    <a href="{{ path('app_admin_document_new') }}" class="button-send" role="button"><i class="fa-solid fa-plus"></i> Ajouter un document pour les administrateurs</a>
    <form id="searchForm" method="get" action="{{ path('app_admin_documents') }}">
        <br>
        <div style="position: relative; width: 100%;">
            <input type="text" id="searchInput" name="search" placeholder="Rechercher un document">
            <i class="fa-solid fa-search search-icon"></i>
        </div>

    </form>

    <div id="documentsGrid" class="documents-container" data-controller="documentAdm">
        {% if is_granted('ROLE_ADMIN') %}
            {% if documents is not empty %}
                {% for document in documents %}
                    {% if document.isAdminOnly == true %}
                        <a href="{{ path('app_admin_document_show', {id: document.id}) }}">
                            <div class="document-card" title="{{ document.title }}">
                                {% set fileExtension = document.filePath|split('.')|last %}
                                
                                {% set fileIcon = {
                                    'pdf': 'fa-file-pdf',
                                    'docx': 'fa-file-word',
                                    'xlsx': 'fa-file-excel',
                                    'csv': 'fa-file-csv',
                                    'png': 'fa-file-image',
                                    'jpg': 'fa-file-image',
                                    'jpeg': 'fa-file-image',
                                    'gif': 'fa-file-image',
                                    'svg': 'fa-file-image',
                                    'bmp': 'fa-file-image',
                                    'tiff': 'fa-file-image',
                                    'txt': 'fa-file-alt',
                                    'md': 'fa-file-alt',
                                    'rtf': 'fa-file-alt',
                                    'pptx': 'fa-file-powerpoint',
                                    'ppt': 'fa-file-powerpoint',
                                    'zip': 'fa-file-archive',
                                    'rar': 'fa-file-archive',
                                    '7z': 'fa-file-archive',
                                    'tar': 'fa-file-archive',
                                    'gz': 'fa-file-archive',
                                    'mp3': 'fa-file-audio',
                                    'wav': 'fa-file-audio',
                                    'ogg': 'fa-file-audio',
                                    'flac': 'fa-file-audio',
                                    'mp4': 'fa-file-video',
                                    'avi': 'fa-file-video',
                                    'mkv': 'fa-file-video',
                                    'mov': 'fa-file-video',
                                    'wmv': 'fa-file-video',
                                    'html': 'fa-file-code',
                                    'css': 'fa-file-code',
                                    'js': 'fa-file-code',
                                    'json': 'fa-file-code',
                                    'xml': 'fa-file-code',
                                    'php': 'fa-file-code',
                                    'java': 'fa-file-code',
                                    'py': 'fa-file-code',
                                    'cpp': 'fa-file-code',
                                    'c': 'fa-file-code',
                                    'sh': 'fa-file-code'
                                } [fileExtension] ?? 'fa-file' %}

                                <div class="file-icon">
                                    <i class="fa-solid {{ fileIcon }}"></i>
                                </div>
                                <div class="document-info">
                                    <h2>{{ document.title|capitalize|slice(0, 10) }}</h2>
                                </div>
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}
            {% else %}
                <p>Aucun document</p>
            {% endif %}
        {% endif %}
    </div>

{% endblock %}

templates/pages/document/showDocuments.html.twig
{% extends 'base.html.twig' %}

{% block title %}<i class="fa-solid fa-folder-open"></i> Mes Documents{% endblock %}

{% block body %}
    <h1>Mes Documents</h1>

    {% for label, messages in app.flashes %}
        <div class="alert alert-{{ label }}">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endfor %}

    <br>
    <a href="{{ path('app_document_new') }}" class="button-send" role="button"><i class="fa-solid fa-plus"></i> Ajouter un Document</a>

    <form id="searchForm" method="get" action="{{ path('app_user_documents') }}">
        <br>
        <div style="position: relative; width: 100%;">
            <input type="text" id="searchInput" name="search" placeholder="Rechercher un document">
            <i class="fa-solid fa-search search-icon"></i>
        </div>
    </form>

    <div id="documentsGrid" class="documents-container" data-controller="document">
        {% if is_granted('ROLE_USER') %}
            {% if documents is not empty %}
                {% for document in documents %}
                    {% if document.isAdminOnly == false %}
                        <a href="{{ path('app_document_show', {id: document.id}) }}">
                            <div class="document-card" title="{{ document.title }}">
                                {% set fileExtension = document.filePath|split('.')|last %}
                                
                                {% set fileIcon = {
                                    'pdf': 'fa-file-pdf',
                                    'docx': 'fa-file-word',
                                    'xlsx': 'fa-file-excel',
                                    'csv': 'fa-file-csv',
                                    'png': 'fa-file-image',
                                    'jpg': 'fa-file-image',
                                    'jpeg': 'fa-file-image',
                                    'gif': 'fa-file-image',
                                    'svg': 'fa-file-image',
                                    'bmp': 'fa-file-image',
                                    'tiff': 'fa-file-image',
                                    'txt': 'fa-file-alt',
                                    'md': 'fa-file-alt',
                                    'rtf': 'fa-file-alt',
                                    'pptx': 'fa-file-powerpoint',
                                    'ppt': 'fa-file-powerpoint',
                                    'zip': 'fa-file-archive',
                                    'rar': 'fa-file-archive',
                                    '7z': 'fa-file-archive',
                                    'tar': 'fa-file-archive',
                                    'gz': 'fa-file-archive',
                                    'mp3': 'fa-file-audio',
                                    'wav': 'fa-file-audio',
                                    'ogg': 'fa-file-audio',
                                    'flac': 'fa-file-audio',
                                    'mp4': 'fa-file-video',
                                    'avi': 'fa-file-video',
                                    'mkv': 'fa-file-video',
                                    'mov': 'fa-file-video',
                                    'wmv': 'fa-file-video',
                                    'html': 'fa-file-code',
                                    'css': 'fa-file-code',
                                    'js': 'fa-file-code',
                                    'json': 'fa-file-code',
                                    'xml': 'fa-file-code',
                                    'php': 'fa-file-code',
                                    'java': 'fa-file-code',
                                    'py': 'fa-file-code',
                                    'cpp': 'fa-file-code',
                                    'c': 'fa-file-code',
                                    'sh': 'fa-file-code'
                                } [fileExtension] ?? 'fa-file' %}

                                <div class="file-icon">
                                    <i class="fa-solid {{ fileIcon }}"></i>
                                </div>
                                <div class="document-info">
                                    <h2>{{ document.title|capitalize|slice(0, 10) }}</h2>
                                </div>
                            </div>
                        </a>
                    {% endif %}
                {% endfor %}
            {% else %}
                <p>Aucun document</p>
            {% endif %}
        {% endif %}
    </div>

{% endblock %}