src/Entity/Ticket.php
<?php

namespace App\Entity;

use App\Repository\TicketRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TicketRepository::class)]
class Ticket
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToOne(inversedBy: 'tickets')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    /**
     * @var Collection<int, User>
     */
    #[ORM\ManyToMany(targetEntity: User::class, inversedBy: 'assigned_tickets')]
    private Collection $assigned_to;

    #[ORM\Column(length: 150)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(length: 50)]
    private ?string $status = null;

    #[ORM\Column(length: 50)]
    private ?string $priority = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(type: 'boolean')]
    private $isDeleted = false;

    public function __construct()
    {
        $this->assigned_to = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, User>
     */
    public function getAssignedTo(): Collection
    {
        return $this->assigned_to;
    }

    public function addAssignedTo(User $assignedTo): static
    {
        if (!$this->assigned_to->contains($assignedTo)) {
            $this->assigned_to->add($assignedTo);
        }

        return $this;
    }

    public function removeAssignedTo(User $assignedTo): static
    {
        $this->assigned_to->removeElement($assignedTo);

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getPriority(): ?string
    {
        return $this->priority;
    }

    public function setPriority(string $priority): static
    {
        $this->priority = $priority;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getIsDeleted(): bool
    {
        return $this->isDeleted;
    }

    public function setIsDeleted(bool $isDeleted): self
    {
        $this->isDeleted = $isDeleted;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_USERNAME', fields: ['username'])]
#[UniqueEntity(fields: ['username'], message: 'Se compte exist déjà.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $username = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column(type: 'json')]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $position = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $job = null;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])]
    private ?UserProfile $profile = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Department $department = null;

    /**
     * @var Collection<int, Ticket>
     */
    #[ORM\OneToMany(targetEntity: Ticket::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $tickets;

    /**
     * @var Collection<int, Ticket>
     */
    #[ORM\ManyToMany(targetEntity: Ticket::class, mappedBy: 'assigned_to')]
    private Collection $assigned_tickets;

    /**
     * @var Collection<int, Leave>
     */
    #[ORM\OneToMany(targetEntity: Leave::class, mappedBy: 'user')]
    private Collection $leaves;

    /**
     * @var Collection<int, Document>
     */
    #[ORM\OneToMany(targetEntity: Document::class, mappedBy: 'created_by')]
    private Collection $documents;

    /**
     * @var Collection<int, Event>
     */
    #[ORM\OneToMany(targetEntity: Event::class, mappedBy: 'created_by')]
    private Collection $events;

    /**
     * @var Collection<int, Newsletter>
     */
    #[ORM\OneToMany(targetEntity: Newsletter::class, mappedBy: 'created_by')]
    private Collection $newsletters;

    /**
     * @var Collection<int, Project>
     */
    #[ORM\OneToMany(targetEntity: Project::class, mappedBy: 'created_by')]
    private Collection $projects;

    /**
     * @var Collection<int, Task>
     */
    #[ORM\ManyToMany(targetEntity: Task::class, mappedBy: 'assigned_to')]
    private Collection $tasks;

    /**
     * @var Collection<int, Training>
     */
    #[ORM\OneToMany(targetEntity: Training::class, mappedBy: 'created_by')]
    private Collection $trainings;

    /**
     * @var Collection<int, Registration>
     */
    #[ORM\OneToMany(targetEntity: Registration::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $registrations;

    /**
     * @var Collection<int, Topic>
     */
    #[ORM\OneToMany(targetEntity: Topic::class, mappedBy: 'created_by')]
    private Collection $topics;

    /**
     * @var Collection<int, Post>
     */
    #[ORM\OneToMany(targetEntity: Post::class, mappedBy: 'created_by')]
    private Collection $posts;

    /**
     * @var Collection<int, VehicleReservation>
     */
    #[ORM\OneToMany(targetEntity: VehicleReservation::class, mappedBy: 'user')]
    private Collection $vehicleReservations;

    /**
     * @var Collection<int, RoomReservation>
     */
    #[ORM\ManyToMany(targetEntity: RoomReservation::class, mappedBy: 'assigned_to')]
    private Collection $roomReservations;

    /**
     * @var Collection<int, Link>
     */
    #[ORM\OneToMany(targetEntity: Link::class, mappedBy: 'user')]
    private Collection $links;

    /**
     * @var Collection<int, CulturalEventTicket>
     */
    #[ORM\OneToMany(targetEntity: CulturalEventTicket::class, mappedBy: 'created_by')]
    private Collection $created_at;

    public function __construct()
    {
        $this->tickets = new ArrayCollection();
        $this->assigned_tickets = new ArrayCollection();
        $this->leaves = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->events = new ArrayCollection();
        $this->newsletters = new ArrayCollection();
        $this->projects = new ArrayCollection();
        $this->tasks = new ArrayCollection();
        $this->trainings = new ArrayCollection();
        $this->registrations = new ArrayCollection();
        $this->topics = new ArrayCollection();
        $this->posts = new ArrayCollection();
        $this->vehicleReservations = new ArrayCollection();
        $this->roomReservations = new ArrayCollection();
        $this->links = new ArrayCollection();
        $this->created_at = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): static
    {
        $this->position = $position;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->job;
    }

    public function setJob(string $job): static
    {
        $this->job = $job;

        return $this;
    }

    public function getProfile(): ?UserProfile
    {
        return $this->profile;
    }

    public function setProfile(?UserProfile $profile): self
    {
        $this->profile = $profile;
        if ($profile !== null && $profile->getUser() !== $this) {
            $profile->setUser($this);
        }

        return $this;
    }

    public function getDepartment(): ?Department
    {
        return $this->department;
    }

    public function setDepartment(?Department $department): static
    {
        $this->department = $department;

        return $this;
    }

    /**
     * @return Collection<int, Ticket>
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    public function addTicket(Ticket $ticket): static
    {
        if (!$this->tickets->contains($ticket)) {
            $this->tickets->add($ticket);
            $ticket->setUser($this);
        }

        return $this;
    }

    public function removeTicket(Ticket $ticket): static
    {
        if ($this->tickets->removeElement($ticket)) {
            // set the owning side to null (unless already changed)
            if ($ticket->getUser() === $this) {
                $ticket->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Ticket>
     */
    public function getAssignedTickets(): Collection
    {
        return $this->assigned_tickets;
    }

    public function addAssignedTicket(Ticket $assignedTicket): static
    {
        if (!$this->assigned_tickets->contains($assignedTicket)) {
            $this->assigned_tickets->add($assignedTicket);
            $assignedTicket->addAssignedTo($this);
        }

        return $this;
    }

    public function removeAssignedTicket(Ticket $assignedTicket): static
    {
        if ($this->assigned_tickets->removeElement($assignedTicket)) {
            $assignedTicket->removeAssignedTo($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Leave>
     */
    public function getLeaves(): Collection
    {
        return $this->leaves;
    }

    public function addLeaf(Leave $leaf): static
    {
        if (!$this->leaves->contains($leaf)) {
            $this->leaves->add($leaf);
            $leaf->setUser($this);
        }

templates/pages/tickets/adminEditTicket.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier le statut du ticket{% endblock %}

{% block body %}
    <h2>Modifier le statut du ticket</h2>

    <h4>Détails du Ticket</h4>

    <p><strong>Sujet :</strong> {{ ticket.title }}</p>
    <p><strong>Description :</strong> {{ ticket.description | nl2br}}</p>
    <p><strong>Statut :</strong> {{ ticket.status }}</p>
    <p><strong>Priorité :</strong> {{ ticket.priority }}</p>
    <p><strong>Créé le :</strong> {{ ticket.createdAt|date('Y-m-d H:i:s') }}</p>
    <p><strong>Dernière mise à jour :</strong> {{ ticket.updatedAt|date('Y-m-d H:i:s') }}</p>

    {{ form_start(form) }}
        {{ form_row(form.status) }}
        <button type="submit">Enregistrer</button>
    {{ form_end(form) }}

        <a href="{{ path('app_show_tickets') }}">Retour à la liste des tickets</a>
{% endblock %}

templates/pages/tickets/adminShowTicket.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails du ticket{% endblock %}

{% block body %}
<a href="{{ path('app_admin_tickets') }}"><i class="fa-solid fa-arrow-left-long"></i> Retour à la gestion des tickets</a>
<div class="ticket-details">
    <h2>Détails du Ticket</h2>

    <p><strong>Auteur :</strong> {{ ticket.user.username }}</p>
    <p><strong>Sujet :</strong> {{ ticket.title }}</p>
    <p><strong>Description :</strong> {{ ticket.description | nl2br }}</p>
    <p><strong>Statut :</strong> <span class="status {{ ticket.status | lower }}">{{ ticket.status }}</span></p>
    <p><strong>Priorité :</strong>                             {% if ticket.priority == 'low' %}
                                <i class="fa-solid fa-temperature-quarter priority priority-low" title="Priorité : Basse"></i>
                            {% elseif ticket.priority == 'medium' %}
                                <i class="fa-solid fa-temperature-half priority priority-medium" title="Priorité : Moyene"></i>
                            {% elseif ticket.priority == 'high' %}
                                <i class="fa-solid fa-temperature-three-quarters priority priority-high" title="Priorité : Haute"></i>
                            {% elseif ticket.priority == 'very high' %}
                                <i class="fa-solid fa-temperature-full priority priority-very-high" title="Priorité : Très Haute" ></i>
                            {% endif %}</p>
    <p><strong>Créé le :</strong> {{ ticket.createdAt|date('Y-m-d H:i:s') }}</p>
    <p><strong>Dernière mise à jour :</strong> {{ ticket.updatedAt|date('Y-m-d H:i:s') }}</p>

    {% if ticket.isDeleted == 1 %}
        <p class="deleted-info"><strong>Suppression coté utilisateur :</strong> {{ ticket.user.username }} a supprimé son ticket</p>
    {% elseif ticket.isDeleted == 0 %}
        <p><strong>Suppression coté utilisateur :</strong> {{ ticket.user.username }} n'a pas supprimé son ticket</p>
    {% endif %}
</div>
{% endblock %}

templates/pages/tickets/adminTickets.html.twig
{% extends 'base.html.twig' %}

{% block title %}<i class="fa-solid fa-ticket-simple"></i> Gestion des tickets{% endblock %}

{% block body %}
    <h2>Gestion des Tickets</h2>
    <br>
        {% for label, messages in app.flashes %}
        <div class="alert alert-{{ label }}">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endfor %}
    {% if pagination.getTotalItemCount() > 0 %}
        <table>
            <thead>
                <tr>
                    <th>Consulté</th>
                    <th>Utilisateur</th>
                    <th>Titre</th>
                    <th>Description</th>
                    <th>Priorité</th>
                    <th>Créé le</th>
                    <th>Régler</th>
                    <th>Supprimer</th>
                </tr>
            </thead>
            <tbody>
                {% for ticket in pagination.getItems() %}
                    <tr class="{% if ticket.status == 'Closed' %}closed-ticket{% endif %}"> 
                        <td><a href="{{ path('app_ticket_show_admin', {id: ticket.id}) }}"><i class="fa-solid fa-eye" title="Consulté le ticket : {{ ticket.id }} | {{ ticket.title }}, {{ ticket.user.username }}"></i></a></td>
                        <td>{{ ticket.user.username }}</td>
                        <td>{{ ticket.title|length > 55 ? ticket.title|slice(0, 30) ~ '...' : ticket.title  }}</td>
                        <td>{{ ticket.description|length > 25 ? ticket.description|slice(0, 40) ~ '...' : ticket.description }}</td>
                        <td>
                            {% if ticket.priority == 'low' %}
                                <i class="fa-solid fa-temperature-quarter priority priority-low" title="Priorité : Basse"></i>
                            {% elseif ticket.priority == 'medium' %}
                                <i class="fa-solid fa-temperature-half priority priority-medium" title="Priorité : Moyene"></i>
                            {% elseif ticket.priority == 'high' %}
                                <i class="fa-solid fa-temperature-three-quarters priority priority-high" title="Priorité : Haute"></i>
                            {% elseif ticket.priority == 'very high' %}
                                <i class="fa-solid fa-temperature-full priority priority-very-high" title="Priorité : Très Haute" ></i>
                            {% endif %}
                        </td>
                        <td>{{ ticket.createdAt|date('d/m/Y') }}</td>
                        <td>
                            <form method="post" action="{{ path('app_ticket_status_admin', {id: ticket.id}) }}" title="Changer le status du ticket : ID{{ticket.id}} de {{ ticket.user.username }} il sera donc clos" style="display: inline;">
                                <label class="switch">
                                    <input type="checkbox" name="status" value="Closed" 
                                        {% if ticket.status == 'Closed' %}checked{% endif %} 
                                        onchange="this.form.submit()">
                                    <span class="slider round"></span>
                                </label>
                            </form>
                        </td>
                        <td>
                            <form method="post" action="{{ path('app_ticket_delete_admin', {id: ticket.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer définitivement ce ticket ?');">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ticket.id) }}">
                                <button class="button-delete" type="submit"><i class="fa-solid fa-trash-can" title="Supprimer le ticket : ID{{ticket.id}} de {{ ticket.user.username }} définitivement"></i></button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>Aucun ticket trouvé.</p>
    {% endif %}

    {% if pagination.getPageCount() > 1 %}
        {% include 'bundles/KnpPaginatorBundle/Pagination/custom_pagination.html.twig' with { 'pagination': pagination } %}
    {% endif %}
{% endblock %}

templates/pages/tickets/createTicket.html.twig
{% extends 'base.html.twig' %}

{% block title %}Création de Ticket{% endblock %}

{% block body %}
    <h3>Crée un ticket :</h3>

    {% for label, messages in app.flashes %}
        <div class="alert alert-{{ label }}">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endfor %}

{{ form_start(form) }}
        {{ form_widget(form) }}
        <input type="hidden" name="_csrf_token" value="{{ csrf_token('authenticate') }}">
        <button type="submit">Crée le ticket</button>
    {{ form_end(form) }}

    <h3>Ce ticket sera envoyé au service informatique :</h3>

    <section class="tickets_listofmoderation">
        <ul>
            {% for admin in admins %}
                <li>
                    <div>
                        <i class="fa-solid fa-user-shield"></i> {{ admin.firstName | capitalize }} {{ admin.lastName  | capitalize }}    
                    </div>
                </li>
            {% endfor %}
        </ul>
    </section>
{% endblock %}

templates/pages/tickets/editTicket.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier le Ticket{% endblock %}

{% block body %}

    <a href="{{ path('app_ticket_show', {id: ticket.id}) }}"><i class="fa-solid fa-arrow-left-long"></i> Quitter sans modifier</a>
    <h2>Modifier le Ticket</h2>

    {% for label, messages in app.flashes %}
        <div class="alert alert-{{ label }}">
            {% for message in messages %}
                {{ message }}
            {% endfor %}
        </div>
    {% endfor %}

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button class="button-edit" type="submit">Enregistrer les modifications</button>
    {{ form_end(form) }}

    <a href="{{ path('app_show_tickets') }}"><i class="fa-solid fa-table-cells"></i> Retour à la liste des tickets</a>
{% endblock %}

templates/pages/tickets/showTicket.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détails du ticket{% endblock %}

{% block body %}
    <div class="ticket-details">
        <a href="{{ path('app_show_tickets') }}"><i class="fa-solid fa-arrow-left-long"></i> Retour à la liste des tickets</a>

        <h2>Détails du Ticket</h2>

        <p><strong>Sujet :</strong> {{ ticket.title }}</p>
        <p><strong>Description :</strong> {{ ticket.description | nl2br }}</p>
        <p><strong>Statut :</strong> {{ ticket.status }}</p>
        <p><strong>Priorité :</strong> {{ ticket.priority }}</p>
        <p><strong>Créé le :</strong> {{ ticket.createdAt|date('Y-m-d H:i:s') }}</p>
        <p><strong>Dernière mise à jour :</strong> {{ ticket.updatedAt|date('Y-m-d H:i:s') }}</p>
    
        {% if ticket.status == "Open" %}
            <button class="button-edit" onclick="window.location.href='{{ path('app_ticket_modify', {id: ticket.id}) }}'">Modifier mon ticket</button>        
        {% elseif ticket.status == "Closed" %}
            <h3 class="ticket-closed-message">Ce ticket est résolu !</h3>
        {% endif %}
    </div>
{% endblock %}

templates/pages/tickets/showTickets.html.twig
{% extends 'base.html.twig' %}

{% block title %}<i class="fa-solid fa-ticket"></i> Mes tickets{% endblock %}

{% block body %}
    <h2>Mes Tickets</h2>
    <br>
     <a href="{{ path('app_create_ticket') }}" class="button-send" role="button"><i class="fa-solid fa-plus"></i> Nouveau ticket</a>
    <br>
    {% if pagination.getTotalItemCount() > 0 %}
        <table>
            <thead>
                <tr>
                    <th>Consulté</th>
                    <th>Titre</th>
                    <th>Description</th>
                    <th>Priorité</th>
                    <th>Créé le</th>
                    <th>Supprimer</th>
                </tr>
            </thead>
            <tbody>
                {% for ticket in pagination.getItems() %}
                    <tr class="{% if ticket.status == 'Closed' %}closed-ticket{% endif %}"> 
                        <td><a href="{{ path('app_ticket_show', {id: ticket.id}) }}"><i class="fa-solid fa-eye" title="Consulté le ticket : ID{{ ticket.id }}"></i></a></td>
                        <td>{{ ticket.title|length > 55 ? ticket.title|slice(0, 30) ~ '...' : ticket.title  }}</td>
                        <td>{{ ticket.description|length > 25 ? ticket.description|slice(0, 40) ~ '...' : ticket.description }}</td>
                        <td>
                            {% if ticket.priority == 'low' %}
                                <i class="fa-solid fa-temperature-quarter priority priority-low" title="Priorité : Basse"></i>
                            {% elseif ticket.priority == 'medium' %}
                                <i class="fa-solid fa-temperature-half priority priority-medium" title="Priorité : Moyene"></i>
                            {% elseif ticket.priority == 'high' %}
                                <i class="fa-solid fa-temperature-three-quarters priority priority-high" title="Priorité : Haute"></i>
                            {% elseif ticket.priority == 'very high' %}
                                <i class="fa-solid fa-temperature-full priority priority-very-high" title="Priorité : Très Haute" ></i>
                            {% endif %}
                        </td>
                        <td>{{ ticket.createdAt|date('d/m/Y') }}</td>
                        <td>
                            <form method="post" action="{{ path('app_ticket_delete', {id: ticket.id}) }}" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer ce ticket ? cela n'entrainera pas une annulation du ticket au pret du service informatique.');">
                                <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ ticket.id) }}">
                                <button class="button-delete" type="submit"><i class="fa-solid fa-trash-can" title="Supprimer le ticket : ID{{ ticket.id }} de {{ ticket.user.username }}"></i></button>
                            </form>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <br>
        <p>Aucun ticket trouvé.</p>
    {% endif %}

    {% if pagination.getPageCount() > 1 %}
        {% include 'bundles/KnpPaginatorBundle/Pagination/custom_pagination.html.twig' with { 'pagination': pagination } %}
    {% endif %}
{% endblock %}