src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_USERNAME', fields: ['username'])]
#[UniqueEntity(fields: ['username'], message: 'Se compte exist déjà.')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $username = null;

    /**
     * @var list<string> The user roles
     */
    #[ORM\Column(type: 'json')]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 255)]
    private ?string $first_name = null;

    #[ORM\Column(length: 255)]
    private ?string $last_name = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $position = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $job = null;

    #[ORM\OneToOne(mappedBy: 'user', cascade: ['persist', 'remove'])]
    private ?UserProfile $profile = null;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Department $department = null;

    /**
     * @var Collection<int, Ticket>
     */
    #[ORM\OneToMany(targetEntity: Ticket::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $tickets;

    /**
     * @var Collection<int, Ticket>
     */
    #[ORM\ManyToMany(targetEntity: Ticket::class, mappedBy: 'assigned_to')]
    private Collection $assigned_tickets;

    /**
     * @var Collection<int, Leave>
     */
    #[ORM\OneToMany(targetEntity: Leave::class, mappedBy: 'user')]
    private Collection $leaves;

    /**
     * @var Collection<int, Document>
     */
    #[ORM\OneToMany(targetEntity: Document::class, mappedBy: 'created_by')]
    private Collection $documents;

    /**
     * @var Collection<int, Event>
     */
    #[ORM\OneToMany(targetEntity: Event::class, mappedBy: 'created_by')]
    private Collection $events;

    /**
     * @var Collection<int, Newsletter>
     */
    #[ORM\OneToMany(targetEntity: Newsletter::class, mappedBy: 'created_by')]
    private Collection $newsletters;

    /**
     * @var Collection<int, Project>
     */
    #[ORM\OneToMany(targetEntity: Project::class, mappedBy: 'created_by')]
    private Collection $projects;

    /**
     * @var Collection<int, Task>
     */
    #[ORM\ManyToMany(targetEntity: Task::class, mappedBy: 'assigned_to')]
    private Collection $tasks;

    /**
     * @var Collection<int, Training>
     */
    #[ORM\OneToMany(targetEntity: Training::class, mappedBy: 'created_by')]
    private Collection $trainings;

    /**
     * @var Collection<int, Registration>
     */
    #[ORM\OneToMany(targetEntity: Registration::class, mappedBy: 'user', orphanRemoval: true)]
    private Collection $registrations;

    /**
     * @var Collection<int, Topic>
     */
    #[ORM\OneToMany(targetEntity: Topic::class, mappedBy: 'created_by')]
    private Collection $topics;

    /**
     * @var Collection<int, Post>
     */
    #[ORM\OneToMany(targetEntity: Post::class, mappedBy: 'created_by')]
    private Collection $posts;

    /**
     * @var Collection<int, VehicleReservation>
     */
    #[ORM\OneToMany(targetEntity: VehicleReservation::class, mappedBy: 'user')]
    private Collection $vehicleReservations;

    /**
     * @var Collection<int, RoomReservation>
     */
    #[ORM\ManyToMany(targetEntity: RoomReservation::class, mappedBy: 'assigned_to')]
    private Collection $roomReservations;

    /**
     * @var Collection<int, Link>
     */
    #[ORM\OneToMany(targetEntity: Link::class, mappedBy: 'user')]
    private Collection $links;

    /**
     * @var Collection<int, CulturalEventTicket>
     */
    #[ORM\OneToMany(targetEntity: CulturalEventTicket::class, mappedBy: 'created_by')]
    private Collection $created_at;

    public function __construct()
    {
        $this->tickets = new ArrayCollection();
        $this->assigned_tickets = new ArrayCollection();
        $this->leaves = new ArrayCollection();
        $this->documents = new ArrayCollection();
        $this->events = new ArrayCollection();
        $this->newsletters = new ArrayCollection();
        $this->projects = new ArrayCollection();
        $this->tasks = new ArrayCollection();
        $this->trainings = new ArrayCollection();
        $this->registrations = new ArrayCollection();
        $this->topics = new ArrayCollection();
        $this->posts = new ArrayCollection();
        $this->vehicleReservations = new ArrayCollection();
        $this->roomReservations = new ArrayCollection();
        $this->links = new ArrayCollection();
        $this->created_at = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    /**
     * @see UserInterface
     *
     * @return list<string>
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    /**
     * @param list<string> $roles
     */
    public function setRoles(array $roles): static
    {
        $this->roles = $roles;

        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): static
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): static
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPosition(): ?string
    {
        return $this->position;
    }

    public function setPosition(string $position): static
    {
        $this->position = $position;

        return $this;
    }

    public function getJob(): ?string
    {
        return $this->job;
    }

    public function setJob(string $job): static
    {
        $this->job = $job;

        return $this;
    }

    public function getProfile(): ?UserProfile
    {
        return $this->profile;
    }

    public function setProfile(?UserProfile $profile): self
    {
        $this->profile = $profile;
        if ($profile !== null && $profile->getUser() !== $this) {
            $profile->setUser($this);
        }

        return $this;
    }

    public function getDepartment(): ?Department
    {
        return $this->department;
    }

    public function setDepartment(?Department $department): static
    {
        $this->department = $department;

        return $this;
    }

    /**
     * @return Collection<int, Ticket>
     */
    public function getTickets(): Collection
    {
        return $this->tickets;
    }

    public function addTicket(Ticket $ticket): static
    {
        if (!$this->tickets->contains($ticket)) {
            $this->tickets->add($ticket);
            $ticket->setUser($this);
        }

        return $this;
    }

    public function removeTicket(Ticket $ticket): static
    {
        if ($this->tickets->removeElement($ticket)) {
            // set the owning side to null (unless already changed)
            if ($ticket->getUser() === $this) {
                $ticket->setUser(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Ticket>
     */
    public function getAssignedTickets(): Collection
    {
        return $this->assigned_tickets;
    }

    public function addAssignedTicket(Ticket $assignedTicket): static
    {
        if (!$this->assigned_tickets->contains($assignedTicket)) {
            $this->assigned_tickets->add($assignedTicket);
            $assignedTicket->addAssignedTo($this);
        }

        return $this;
    }

    public function removeAssignedTicket(Ticket $assignedTicket): static
    {
        if ($this->assigned_tickets->removeElement($assignedTicket)) {
            $assignedTicket->removeAssignedTo($this);
        }

        return $this;
    }

    /**
     * @return Collection<int, Leave>
     */
    public function getLeaves(): Collection
    {
        return $this->leaves;
    }

    public function addLeaf(Leave $leaf): static
    {
        if (!$this->leaves->contains($leaf)) {
            $this->leaves->add($leaf);
            $leaf->setUser($this);
        }

src/Entity/UserProfile.php
<?php

namespace App\Entity;

use App\Repository\UserProfileRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: UserProfileRepository::class)]
class UserProfile
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $address = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $phoneFixed = null;

    #[ORM\Column(length: 10, nullable: true)]
    private ?string $phoneMobile = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $avatar = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $bio = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $linkedin_url = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $twitter_handle = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $updated_at = null;

    #[ORM\Column(length: 30, nullable: true)]
    private ?string $style = null;

    #[ORM\OneToOne(inversedBy: 'profile', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\ManyToOne(inversedBy: 'userProfiles')]
    private ?Department $department = null;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
        $this->updated_at = new \DateTimeImmutable();
    }
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getPhoneFixed(): ?string
    {
        return $this->phoneFixed;
    }

    public function setPhoneFixed(?string $phoneFixed): self
    {
        $this->phoneFixed = $phoneFixed;
        return $this;
    }

    public function getPhoneMobile(): ?string
    {
        return $this->phoneMobile;
    }

    public function setPhoneMobile(?string $phoneMobile): self
    {
        $this->phoneMobile = $phoneMobile;
        return $this;
    }

    public function getAvatar(): ?string
    {
        return $this->avatar;
    }

    public function setAvatar(string $avatar): static
    {
        $this->avatar = $avatar;

        return $this;
    }

    public function getBio(): ?string
    {
        return $this->bio;
    }

    public function setBio(?string $bio): static
    {
        $this->bio = $bio;

        return $this;
    }

    public function getLinkedinUrl(): ?string
    {
        return $this->linkedin_url;
    }

    public function setLinkedinUrl(?string $linkedin_url): static
    {
        $this->linkedin_url = $linkedin_url;

        return $this;
    }

    public function getTwitterHandle(): ?string
    {
        return $this->twitter_handle;
    }

    public function setTwitterHandle(?string $twitter_handle): static
    {
        $this->twitter_handle = $twitter_handle;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeImmutable
    {
        return $this->updated_at;
    }

    public function setUpdatedAt(\DateTimeImmutable $updated_at): static
    {
        $this->updated_at = $updated_at;

        return $this;
    }

    public function getStyle(): ?string
    {
        return $this->style;
    }

    public function setStyle(?string $style): static
    {
        $this->style = $style;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getDepartment(): ?Department
    {
        return $this->department;
    }

    public function setDepartment(?Department $department): static
    {
        $this->department = $department;

        return $this;
    }
}

templates/pages/profile/adminEditProfile.html.twig
{% extends 'base.html.twig' %}

{% block title %}<i class="fa-solid fa-shield-halved"></i> Modification profil utilisateur{% endblock %}

{% block body %}
<div class="edit-profile">
<a href="{{ path('app_public_profile', {id: user.profile.id}) }}"><i class="fa-solid fa-arrow-left-long"></i> Quitter sans modifier</a>
    <h2>Modifier le profil de {{ user.firstName }} {{ user.lastName }}</h2>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit"><i class="fa-solid fa-shield-halved"></i> Enregistrer les modifications</button>
    {{ form_end(form) }}
</div>
{% endblock %}

templates/pages/profile/allProfiles.html.twig
{% extends 'base.html.twig' %}

{% block title %}<i class="fa-solid fa-users"></i> Liste des profils utilisateurs{% endblock %}

{% block body %}
    <div class="profiles-container" data-controller="profile">
        <h1>Tous les utilisateurs</h1>

        <form id="searchForm" method="get" action="{{ path('app_all_profiles') }}">
            <div style="position: relative; width: 100%;">
                <input type="text" id="searchInput" name="search" value="{{ searchTerm }}" placeholder="Rechercher un utilisateur">
                <i class="fa-solid fa-search search-icon"></i>
            </div>

            <div class="filters-wrapper">
                <div class="filter-container">
                    <label for="positionFilter"><i class="fa-solid fa-people-group main-color"></i> Service :</label>
                    <select id="positionFilter" name="position">
                        <option value="">Tous</option>
                        {% for value, label in {
                            'Relais Petite Enfance "À Mini Pas"': 'Relais Petite Enfance "À Mini Pas"',
                            'Service Jeunesse': 'Service Jeunesse',
                            'Actions pour les Personnes Âgées et/ou en Situation de Handicap (SPASAD)': 'Actions pour les Personnes Âgées et/ou en Situation de Handicap (SPASAD)',
                            'Transport à la Demande (TAD)': 'Transport à la Demande (TAD)',
                            'Gestion des Déchets': 'Gestion des Déchets',
                            'Culture': 'Culture',
                            'Tourisme': 'Tourisme',
                            'Service Informatique': 'Service Informatique'
                        } %}
                            <option value="{{ value }}" {{ app.request.query.get('position') == value ? 'selected' : '' }}>{{ label }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="filter-container">
                    <label for="jobFilter"><i class="fa-solid fa-wrench main-color"></i> Profession :</label>
                    <select id="jobFilter" name="job">
                        <option value="">Tous</option>
                        {% for job in jobs %}
                            <option value="{{ job }}" {{ app.request.query.get('job') == job ? 'selected' : '' }}>{{ job }}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="filter-container">
                    <label for="departmentFilter"><i class="fa-solid fa-location-dot main-color"></i> Lieux de travail :</label>
                    <select id="departmentFilter" name="department">
                        <option value="">Tous</option>
                        {% for department in departments %}
                            <option value="{{ department.id }}" {{ app.request.query.get('department') == department.id ? 'selected' : '' }}>{{ department.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                
                <button type="button" id="resetButton" class="reset-button"><i class="fa-solid fa-eraser"></i> Effacer la recherche</button>
            </div>
        </form>



        <div id="profilesGrid" class="profiles-grid">
            {% for user in pagination.getItems() %}
                <div class="profile-card">
                    {% if user.profile %}

                        {% if user.profile.avatar %}
                            <img src="{{ user.profile.avatar ? asset('uploads/profile_images/' ~ user.profile.avatar) : asset('images/profile-placeholder.jpg') }}" 
                             alt="Photo de profil de {{ user.firstname }} {{ user.lastname }}" 
                             class="profile-image">
                        {% else %}
                            <img class="profile-image" src="uploads\profile_images\default-avatar.png" alt="Photo de profil par defaut">
                        {% endif %}
                        
                        <h2><i class="fa-solid fa-circle-user main-color"></i> {{ user.firstname | capitalize }} {{ user.lastname | capitalize  }}</h2>

                        {% if user.profile.phoneFixed %}
                            <p><i class="fa-solid fa-phone main-color"></i> : {{ user.profile.phoneFixed }}</p>
                        {% else %}
                            <p><i class="fa-solid fa-phone main-color"></i> : Non communiquer</p>
                        {% endif %}

                        {% if user.profile.phoneMobile %}
                            <p><i class="fa-solid fa-mobile main-color"></i> : {{ user.profile.phoneMobile }}</p>
                        {% else %}
                            <p><i class="fa-solid fa-mobile main-color"></i> : Non communiquer</p>
                        {% endif %}

                        {% if user.profile.address %}
                            <p><i class="fa-solid fa-map-location-dot main-color"></i> : {{ user.profile.address |slice(0, 20) ~ '...' }}</p>
                        {% else %}
                            <p><i class="fa-solid fa-map-location-dot main-color"></i> : Non communiquer</p>
                        {% endif %}
                    
                        <a href="{{ path('app_public_profile', { id: user.id }) }}" class="view-profile"><i class="fa-regular fa-address-card"></i> Voir le profil</a>
                    {% else %}
                        <div>
                            <h2><i class="fa-solid fa-circle-user main-color"></i> {{ user.firstname | capitalize }} {{ user.lastname | capitalize  }}</h2>
                            <p><em>Pas d'information complémentaire,  cette utilisateur n'a pas remplis son profil dans <a href={{ path('app_public_profile', { id: user.id }) }}>Menu/Mon profil</a></em></p>
                        </div>
                    {% endif %}
                </div>
            {% else %}
                <p>Aucun profil utilisateur trouvé</p>
            {% endfor %}
        </div>
    </div>
{% endblock %}

templates/pages/profile/all_profiles.html.twig
{% extends 'base.html.twig' %}

{% block title %}<i class="fa-solid fa-users"></i> Liste des profils utilisateurs{% endblock %}

{% block body %}
    <div class="profiles-container">
        <h1>Tous les utilisateurs</h1>

        <div class="profiles-grid">
            {% for user in pagination.getItems() %}
                <div class="profile-card">
                    {% if user.profile %}
                        <img src="{{ user.profile.avatar ? asset('uploads/profile_images/' ~ user.profile.avatar) : asset('images/profile-placeholder.jpg') }}" 
                             alt="Photo de profil de {{ user.firstname }} {{ user.lastname }}" 
                             class="profile-image">
                        <h2>{{ user.firstname }} {{ user.lastname }}</h2>
                        <p>{{ user.profile.phone }}</p>
                        <p>{{ user.profile.address }}</p>
                        {# <p>{{ user.profile.department.name }}</p> #}
                        <a href="{{ path('app_public_profile', { id: user.id }) }}" class="view-profile">Voir le profil</a>
                    {% else %}
                        <div class="profile-placeholder">
                            <h2>{{ user.username }}</h2>
                            <p>Pas d'information complémentaire</p>
                        </div>
                    {% endif %}
                </div>
            {% else %}
                <p>Aucun profil utilisateur trouvé</p>
            {% endfor %}
        </div>

        {% if pagination.getPageCount() > 1 %}
            {% include 'bundles/KnpPaginatorBundle/Pagination/custom_pagination.html.twig' with { 'pagination': pagination } %}
        {% endif %}
    </div>
{% endblock %}

templates/pages/profile/profile.html.twig
{% extends 'base.html.twig' %}

{% block title %}<i class="fa-solid fa-user"></i> Mon Profil - {{ app.user.firstName | capitalize }} {{ app.user.lastName | capitalize }}{% endblock %}

{% block body %}

<div class="example-wrapper">
    <h1>Mon Profil</h1>
    <div class="profile-picture">
        <img src="{{ asset(avatarPath) }}" alt="Photo de profil de {{ app.user.firstName | capitalize }} {{ app.user.lastName | capitalize }}">
    </div>
        <form action="{{ path('app_delete_avatar') }}" method="post" style="margin-top: 10px;">
        <button type="submit" class="button-delete" title="Vos photos sont stockées sur l'intranet. Vous pouvez les supprimer définitivement à tout moment. Lorsque vous changez de photo, l'ancienne est automatiquement supprimée. Vous restez maître de tous vos contenus.">Supprimer ma photo de profil</button>
    </form>

    {{ form_start(form) }}
        {{ form_widget(form) }}
        <button type="submit" ><i class="fa-solid fa-floppy-disk"></i> Sauvegarder</button>
    {{ form_end(form) }}


</div>

{% endblock %}

templates/pages/profile/publicProfile.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recherche de profil{% endblock %}

{% block body %}
<div class="user-profile">
    <h1>Profil utilisateur de {{ user.firstName }} {{ user.lastName }}</h1>

    {% if profile %}
        <div class="user-details">
            <a href="{{ path('app_all_profiles') }}"><i class="fa-solid fa-arrow-left-long"></i> Retour a la liste d'utilisateurs</a>
            <br>
            <br>
            {% set avatarPath = profile.avatar ? '/uploads/profile_images/' ~ profile.avatar : '/uploads/profile_images/default-avatar.png' %}
            
            <img src="{{ avatarPath }}" alt="Avatar de {{ user.firstName }}" class="user-avatar" style="width: 150px; height: 150px; border-radius: 50%; object-fit: cover;">
            <br>
            <p><strong><i class="fa-solid fa-envelope main-color"></i> Adresse email:</strong> <a href="mailto:{{ user.email }}">{{ user.email }}</a></p>

            {% if user.profile.phoneFixed %}
                <p><strong><i class="fa-solid fa-square-phone main-color"></i> Numéro de téléphone fixe :</strong> {{ user.profile.phoneFixed }}</p>
                {% else %}
                <p><strong><i class="fa-solid fa-square-phone main-color"></i> Numéro de téléphone fixe :</strong> <em>Non communiquer</em></p>
            {% endif %}

            {% if user.profile.phoneMobile %}
                <p><strong><i class="fa-solid fa-mobile-screen main-color"></i> Numéro de téléphone portable :</strong> {{ user.profile.phoneMobile }}</p>
                {% else %}
                <p><strong><i class="fa-solid fa-mobile-screen main-color"></i> Numéro de téléphone portable :</strong> <em>Non communiquer</em></p>
            {% endif %}
            

            {% if profile.bio %}
                <p><strong><i class="fa-solid fa-book main-color"></i> Bio:</strong> {{ profile.bio }}</p>
            {% else %}
                <p><strong><i class="fa-solid fa-book main-color"></i> Bio:</strong> <em>Non communiquer</em></p>
            {% endif %}

            {% if profile.linkedinUrl %}
                <p><strong><i class="fa-brands fa-linkedin main-color"></i> LinkedIn:</strong> <a href="{{ profile.linkedinUrl }}" target="_blank">{{ profile.linkedinUrl }}</a></p>
            {% else %}
                <p><strong><i class="fa-brands fa-linkedin main-color"></i> LinkedIn:</strong> <em>Non communiquer</em></p>
            {% endif %}

            <p><strong><i class="fa-solid fa-map-location-dot main-color"></i> Lieux de travail :</strong> {{ profile.user.department.name }}</p>
        
            {% if is_granted('ROLE_ADMIN') %}
            <br>
            <h6><i class="fa-solid fa-shield-halved"></i> Outils Administrateur</h6>
                <a href="{{ path('app_edit_profile', {id: user.id}) }}" class="button-edit"><i class="fa-solid fa-hammer"></i> Modifier le profil de l'utilisateur</a>
                <form action="{{ path('app_delete_user', {id: user.id}) }}" method="post" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet utilisateur ?');" style="display: inline;">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete-user-' ~ user.id) }}">
                    <button type="submit" class="button-delete strong"><i class="fa-solid fa-trash"></i> Supprimer l'utilisateur</button>
                </form>
            {% endif %}

        </div>

    {% else %}
    <a href="{{ path('app_all_profiles') }}"><i class="fa-solid fa-arrow-left-long"></i> Retour a la liste d'utilisateurs</a>
        <p class="user-no-profile">Les informations de cet utilisateur ne sont pas encore disponibles...</p>
        <br>
            {% if is_granted('ROLE_ADMIN') %}
            
            <br>
            <h6><i class="fa-solid fa-shield-halved"></i> Outils Administrateur</h6>
                <a href="{{ path('app_edit_profile', {id: user.id}) }}" class="button-edit"><i class="fa-solid fa-hammer"></i> Modifier le profil de l'utilisateur</a>
                <form action="{{ path('app_delete_user', {id: user.id}) }}" method="post" onsubmit="return confirm('Êtes-vous sûr de vouloir supprimer cet utilisateur ?');" style="display: inline;">
                    <input type="hidden" name="_token" value="{{ csrf_token('delete-user-' ~ user.id) }}">
                    <button type="submit" class="button-delete strong"><i class="fa-solid fa-trash"></i> Supprimer l'utilisateur</button>
                </form>
            {% endif %}
    {% endif %}
</div>

{% endblock %}